-- Synced with magic numbers. Location for respawn & tower return.
SPAWN_X = 490
SPAWN_Y = -1815


--
-- MATWAND
--
SELECTED_BRUSH = "RAKSA_SELECTED_BRUSH"
DEFAULT_BRUSH = "4" -- 10px brush
-- NOTE: The reticle entity file has the actual default brush image defined
-- TODO: Dynamic first load?

BRUSH_GRID_SIZE = "RAKSA_BRUSH_GRID_SIZE"
BRUSH_DEFAULT_GRID_SIZE = "1"

SELECTED_MATERIAL = "RAKSA_SELECTED_MATERIAL"
SELECTED_MATERIAL_DEFAULT = "soil"
SELECTED_MATERIAL_ICON = "RAKSA_SELECTED_MATERIAL_ICON"
SELECTED_MATERIAL_ICON_DEFAULT = "mods/raksa/files/gfx/material_icons/soil.png"

ERASER_MODE = "RAKSA_ERASER_MODE"
ERASER_MODE_SOLIDS = "solids"
ERASER_MODE_LIQUIDS = "liquids"
ERASER_MODE_BOTH = "both"
ERASER_MODE_DEFAULT = ERASER_MODE_SOLIDS


ERASER_SIZE = "RAKSA_ERASER_SIZE"
ERASER_SIZE_DEFAULT = "2" -- default


--
-- ENTWAND
--
SELECTED_ENTITY_INDEX = "RAKSA_SELECTED_ENTITY_INDEX"
SELECTED_ENTITY_TYPE = "RAKSA_SELECTED_ENTITY_TYPE"

SELECTED_ENTITY_INDEX_DEFAULT = "93"  -- Sheep.
SELECTED_ENTITY_TYPE_DEFAULT = 1 -- Animals / Creatures


--
-- GUI
--
-- Ninepiece Backgrounds
NPBG_DEFAULT = 0
NPBG_GOLD = 1
NPBG_TAB = 2
NPBG_BLUE = 3
NPBG_BLUE_TAB = 4
NPBG_BROWN = 5
NPBG_BROWN_TAB = 6

ICON_MOUSE_LEFT = "mods/raksa/files/gfx/mouse_left.png"
ICON_MOUSE_RIGHT = "mods/raksa/files/gfx/mouse_right.png"


-- TIME OF DAY
DAWN = 0.73
NOON = 0
DUSK = 0.47
MIDNIGHT = 0.6


-- POWERS
KALMA_IS_IMMORTAL = "RAKSA_IMMORTALITY"
