-- Synced with magic numbers. Location for respawn & tower return.
-- TODO: If IS_VANILLA_MAP
SPAWN_X = 490
SPAWN_Y = -1815

-- Ninepiece Backgrounds
NPBG_DEFAULT = 0
NPBG_GOLD = 1
NPBG_TAB = 2
NPBG_BLUE = 3
NPBG_BLUE_TAB = 4
NPBG_BROWN = 5
NPBG_BROWN_TAB = 6

ICON_MOUSE_LEFT = "mods/raksa/files/gfx/mouse_left.png"
ICON_MOUSE_RIGHT = "mods/raksa/files/gfx/mouse_right.png"

-- TIME OF DAY
DAWN = 0.73
NOON = 0
DUSK = 0.47
MIDNIGHT = 0.6


--
-- MATWAND
--
-- NOTE: The reticle entity file has the actual default brush image defined
-- TODO: Dynamic first load?
SELECTED_BRUSH = "RAKSA_SELECTED_BRUSH"
SELECTED_MATERIAL = "RAKSA_SELECTED_MATERIAL"
SELECTED_MATERIAL_ICON = "RAKSA_SELECTED_MATERIAL_ICON"
BRUSH_GRID_SIZE = "RAKSA_BRUSH_GRID_SIZE"

ERASER_MODE = "RAKSA_ERASER_MODE"
ERASER_MODE_ALL = "ALL"
ERASER_MODE_SELECTED = "SELECTED"
ERASER_MODE_SOLIDS = "[solid]"
ERASER_MODE_LIQUIDS = "[liquid]"
ERASER_MODE_SANDS = "[sand_ground]"
ERASER_MODE_GASES = "[gas]"
ERASER_MODE_FIRE = "[fire]"

ERASER_REPLACE = "RAKSA_ERASER_REPLACE"
ERASER_SHARED_GRID = "RAKSA_ERASER_SHARED_GRID"
ERASER_GRID_SIZE = "RAKSA_ERASER_GRID_SIZE"
ERASER_SIZE = "RAKSA_ERASER_SIZE"

ERASER_PIXEL = "mods/raksa/files/gfx/eraser_pixel.png"
REPLACER_PIXEL = "mods/raksa/files/gfx/replacer_pixel.png"


--
-- ENTWAND
--
SELECTED_ENTITY_INDEX = "RAKSA_SELECTED_ENTITY_INDEX"
SELECTED_ENTITY_TYPE = "RAKSA_SELECTED_ENTITY_TYPE"


--
-- POWERS
--
KALMA_IS_IMMORTAL = "RAKSA_IMMORTALITY"
BINOCULARS_ACTIVE = "RAKSA_BINOCULARS_ACTIVE"

RAIN_ENABLED = "RAKSA_RAIN_ENABLED"
RAIN_COUNT = "RAKSA_RAIN_COUNT"
RAIN_WIDTH = "RAKSA_RAIN_WIDTH"
RAIN_VELOCITY_MIN = "RAKSA_RAIN_VELOCITY_MIN"
RAIN_VELOCITY_MAX = "RAKSA_RAIN_VELOCITY_MAX"
RAIN_GRAVITY = "RAKSA_RAIN_GRAVITY"
RAIN_BOUNCE = "RAKSA_RAIN_BOUNCE"
RAIN_DRAW_LONG = "RAKSA_RAIN_DRAW_AS_LONG"

--
-- OTHER
--
PLAYER_HAS_DIED = "RAKSA_PLAYER_HAS_DIED"
FIRST_LOAD_DONE = "RAKSA_FIRST_LOAD_DONE"


DEFAULTS = {
  -- Matwand
  [SELECTED_BRUSH] = "4", -- 10px brush
  [SELECTED_MATERIAL] = "soil",
  [SELECTED_MATERIAL_ICON] = "mods/raksa/files/gfx/material_icons/soil.png",
  [BRUSH_GRID_SIZE] = "1",
  [ERASER_MODE] = ERASER_MODE_SOLIDS,
  [ERASER_REPLACE] = "0",
  [ERASER_SHARED_GRID] = "1",
  [ERASER_GRID_SIZE] = "1",
  [ERASER_SIZE] = "2",
  -- Entwand
  [SELECTED_ENTITY_INDEX] = "93",  -- Sheep.
  [SELECTED_ENTITY_TYPE] = 1, -- Animals / Creatures
  -- Powers
  [BINOCULARS_ACTIVE] = "0",
  [KALMA_IS_IMMORTAL] = "0",
  [RAIN_ENABLED] = "0",
  [RAIN_COUNT] = 10,
  [RAIN_WIDTH] = 1280,
  [RAIN_VELOCITY_MIN] = "30",
  [RAIN_VELOCITY_MAX] = "60",
  [RAIN_GRAVITY] = "10",
  [RAIN_BOUNCE] = "1",
  [RAIN_DRAW_LONG] = "1",
  -- Other
  [PLAYER_HAS_DIED] = "0",
  [FIRST_LOAD_DONE] = "0",
}
