
SELECTED_BRUSH = "RAKSA_SELECTED_BRUSH"
DEFAULT_BRUSH = "3" -- 5px brush
-- NOTE: The reticle entity file has the actual default brush image defined
-- TODO: Dynamic first load?


SELECTED_MATERIAL = "RAKSA_SELECTED_MATERIAL"
SELECTED_MATERIAL_DEFAULT = "soil"

ERASER_MODE = "RAKSA_ERASER_MODE"
ERASER_MODE_SOLIDS = "solids"
ERASER_MODE_LIQUIDS = "liquids"
ERASER_MODE_BOTH = "both"
ERASER_MODE_DEFAULT = ERASER_MODE_SOLIDS


ERASER_SIZE = "RAKSA_ERASER_SIZE"
ERASER_SIZE_DEFAULT = "2" -- default
