ANIMALS = {
  {path='data/entities/animals/acidshooter.xml',name='Acidshooter'},
  {path='data/entities/animals/acidshooter_weak.xml',name='Acidshooter weak'},	
  {path='data/entities/animals/alchemist.xml',name='Alchemist'},
  {path='data/entities/animals/ant.xml',name='Ant'},
  {path='data/entities/animals/assassin.xml',name='Assassin'},
  {path='data/entities/animals/barfer.xml',name='Barfer'},
  {path='data/entities/animals/bat.xml',name='Bat'},
  {path='data/entities/animals/bigbat.xml',name='Bigbat'},
  {path='data/entities/animals/bigfirebug.xml',name='Bigfirebug'},
  {path='data/entities/animals/bigzombie.xml',name='Bigzombie'},
  {path='data/entities/animals/bigzombiehead.xml',name='Bigzombiehead'},
  {path='data/entities/animals/bigzombietorso.xml',name='Bigzombietorso'},
  {path='data/entities/animals/blob.xml',name='Blob'},
  {path='data/entities/animals/bloodcrystal_physics.xml',name='Bloodcrystal physics'},
  {path='data/entities/animals/bloom.xml',name='Bloom'},
  {path='data/entities/animals/boss_alchemist/boss_alchemist.xml',name='Boss alchemist'},
  {path='data/entities/animals/boss_centipede/boss_centipede.xml',name='Boss three-eye - collect sampo in boss chamber to activate'},
  {path='data/entities/animals/boss_centipede/boss_centipede_minion.xml',name='Boss three-eye minion'},
  {path='data/entities/animals/boss_dragon.xml',name='Boss dragon'},
  {path='data/entities/animals/boss_limbs/boss_limbs.xml',name='Boss limbs'},
  {path='data/entities/animals/boss_limbs/slimeshooter_boss_limbs.xml',name='Boss limbs minion'},
  {path='data/entities/animals/boss_pit/boss_pit.xml',name='Boss pit'},
  {path='data/entities/animals/chest_leggy.xml',name='Chest leggy'},
  {path='data/entities/animals/chest_mimic.xml',name='Chest mimic'},
  {path='data/entities/animals/crystal_physics.xml',name='Crystal physics'},
  {path='data/entities/buildings/darkghost_crystal.xml',name='Darkghost'},
  {path='data/entities/animals/deer.xml',name='Deer'},
  {path='data/entities/animals/drone.xml',name='Drone'},
  {path='data/entities/animals/drone_lasership.xml',name='Drone lasership'},
  {path='data/entities/animals/drone_physics.xml',name='Drone physics'},
  {path='data/entities/animals/duck.xml',name='Duck'},
  {path='data/entities/animals/eel.xml',name='Eel'},
  {path='data/entities/animals/elk.xml',name='Elk'},
  {path='data/entities/animals/enlightened_alchemist.xml',name='Enlightened alchemist'},
  {path='data/entities/animals/failed_alchemist.xml',name='Failed alchemist'},
  {path='data/entities/animals/failed_alchemist_b.xml',name='Failed alchemist b'},
  {path='data/entities/animals/firebug.xml',name='Firebug'},
  {path='data/entities/animals/firemage.xml',name='Firemage'},
  {path='data/entities/animals/firemage_weak.xml',name='Firemage weak'},
  {path='data/entities/animals/fireskull.xml',name='Fireskull'},
  {path='data/entities/animals/fireskull_weak.xml',name='Fireskull weak'},
  {path='data/entities/animals/fish.xml',name='Fish'},
  {path='data/entities/animals/fish_large.xml',name='Fish large'},
  {path='data/entities/animals/flamer.xml',name='Flamer'},
  {path='data/entities/animals/fly.xml',name='Fly'},
  {path='data/entities/animals/frog.xml',name='Frog'},
  {path='data/entities/animals/frog_big.xml',name='Frog big'},
  {path='data/entities/animals/fungus.xml',name='Fungus'},
  {path='data/entities/animals/fungus_big.xml',name='Fungus big'},
  {path='data/entities/animals/gazer.xml',name='Gazer'},
  {path='data/entities/buildings/ghost_crystal.xml',name='Ghost'},
  {path='data/entities/animals/ghoul.xml',name='Ghoul'},
  {path='data/entities/animals/giant.xml',name='Giant'},
  {path='data/entities/animals/giantshooter.xml',name='Giantshooter'},
  {path='data/entities/animals/giantshooter_weak.xml',name='Giantshooter weak'},
  {path='data/entities/animals/goblin_bomb.xml',name='Goblin bomb'},
  {path='data/entities/animals/healerdrone_physics.xml',name='Healerdrone physics'},
  {path='data/entities/animals/icer.xml',name='Icer'},
  {path='data/entities/animals/iceskull.xml',name='Iceskull'},
  {path='data/entities/buildings/lasergun.xml',name='Lasergun'},
  {path='data/entities/animals/lasershooter.xml',name='Lasershooter'},
  {path='data/entities/animals/longleg.xml',name='Longleg'},
  {path='data/entities/animals/lukki/lukki.xml',name='Lukki'},
  {path='data/entities/animals/lukki/lukki_creepy_long.xml',name='Lukki creepy'},
  {path='data/entities/buildings/lukki_eggs.xml',name='Lukki egg'},
  {path='data/entities/animals/lukki/lukki_longleg.xml',name='Lukki longleg'},
  {path='data/entities/animals/lukki/lukki_tiny.xml',name='Lukki tiny'},	
  {path='data/entities/animals/lurker.xml',name='Lurker'},
  {path='data/entities/animals/maggot.xml',name='Maggot'},
  {path='data/entities/animals/miner.xml',name='Miner'},
  {path='data/entities/animals/miner_fire.xml',name='Miner fire'},
  {path='data/entities/animals/miner_santa.xml',name='Miner santa'},
  {path='data/entities/animals/miner_weak.xml',name='Miner weak'},
  {path='data/entities/animals/miniblob.xml',name='Miniblob'},
  {path='data/entities/animals/missilecrab.xml',name='Missilecrab'},
  {path='data/entities/animals/monk.xml',name='Monk'},
  {path='data/entities/animals/necromancer.xml',name='Necromancer'},
  {path='data/entities/animals/necromancer_shop.xml',name='Necromancer shop - Steve - Stevari'},
  {path='data/entities/animals/pebble_physics.xml',name='Pebble physics'},
  {path='data/entities/animals/phantom_a.xml',name='Phantom a'},
  {path='data/entities/animals/phantom_b.xml',name='Phantom b'},
  {path='data/entities/animals/playerghost.xml',name='Playerghost'},
  {path='data/entities/animals/rat.xml',name='Rat'},
  {path='data/entities/animals/roboguard.xml',name='Roboguard'},
  {path='data/entities/animals/scavenger_clusterbomb.xml',name='Scavenger clusterbomb'},
  {path='data/entities/animals/scavenger_grenade.xml',name='Scavenger grenade'},
  {path='data/entities/animals/scavenger_heal.xml',name='Scavenger heal'},
  {path='data/entities/animals/scavenger_invis.xml',name='Scavenger invis'},
  {path='data/entities/animals/scavenger_leader.xml',name='Scavenger leader'},
  {path='data/entities/animals/scavenger_mine.xml',name='Scavenger mine'},
  {path='data/entities/animals/scavenger_poison.xml',name='Scavenger poison'},
  {path='data/entities/animals/scavenger_shield.xml',name='Scavenger shield'},
  {path='data/entities/animals/scavenger_smg.xml',name='Scavenger smg'},
  {path='data/entities/animals/scorpion.xml',name='Scorpion'},
  {path='data/entities/animals/shaman.xml',name='Shaman'},
  {path='data/entities/animals/sheep.xml',name='Sheep'},
  {path='data/entities/animals/sheep_bat.xml',name='Sheep bat'},
  {path='data/entities/animals/sheep_fly.xml',name='Sheep fly'},
  {path='data/entities/animals/shooterflower.xml',name='Shooterflower'},
  {path='data/entities/animals/shotgunner.xml',name='Shotgunner'},
  {path='data/entities/animals/shotgunner_weak.xml',name='Shotgunner weak'},
  {path='data/entities/animals/skullfly.xml',name='Skullfly'},
  {path='data/entities/animals/skullrat.xml',name='Skullrat'},
  {path='data/entities/animals/skycrystal_physics.xml',name='Skycrystal physics'},
  {path='data/entities/animals/slimeshooter.xml',name='Slimeshooter'},
  {path='data/entities/animals/slimeshooter_nontoxic.xml',name='Slimeshooter nontoxic'},
  {path='data/entities/animals/slimeshooter_weak.xml',name='Slimeshooter weak'},
  {path='data/entities/animals/sniper.xml',name='Sniper'},
  {path='data/entities/animals/spearbot.xml',name='Spearbot'},
  {path='data/entities/buildings/spidernest.xml',name='Spidernest'},
  {path='data/entities/animals/spitmonster.xml',name='Spitmonster'},
  {path='data/entities/animals/statue.xml',name='Statue'},
  {path='data/entities/animals/statue_physics.xml',name='Statue physics'},
  {path='data/entities/animals/tank.xml',name='Tank'},
  {path='data/entities/animals/tank_rocket.xml',name='Tank rocket'},
  {path='data/entities/animals/tank_super.xml',name='Tank super'},
  {path='data/entities/animals/tentacler.xml',name='Tentacler'},
  {path='data/entities/animals/tentacler_small.xml',name='Tentacler small'},
  {path='data/entities/animals/thundermage.xml',name='Thundermage'},
  {path='data/entities/animals/thunderskull.xml',name='Thunderskull'},
  {path='data/entities/animals/turret_left.xml',name='Turret left'},
  {path='data/entities/animals/turret_right.xml',name='Turret right'},
  {path='data/entities/animals/ultimate_killer.xml',name='Ultimate killer - horror monster - friend'},
  {path='data/entities/animals/wand_ghost.xml',name='Wand ghost'},
  {path='data/entities/animals/wizard_dark.xml',name='Wizard dark'},
  {path='data/entities/animals/wizard_hearty.xml',name='Wizard hearty'},
  {path='data/entities/animals/wizard_neutral.xml',name='Wizard neutral'},
  {path='data/entities/animals/wizard_poly.xml',name='Wizard poly'},
  {path='data/entities/animals/wizard_returner.xml',name='Wizard returner'},
  {path='data/entities/animals/wizard_swapper.xml',name='Wizard swapper'},
  {path='data/entities/animals/wizard_tele.xml',name='Wizard tele'},
  {path='data/entities/animals/wizard_twitchy.xml',name='Wizard twitchy'},
  {path='data/entities/animals/wolf.xml',name='Wolf'},
  {path='data/entities/animals/worm.xml',name='Worm'},
  {path='data/entities/animals/worm_big.xml',name='Worm big'},
  {path='data/entities/animals/worm_end.xml',name='Worm end'},
  {path='data/entities/animals/worm_skull.xml',name='Worm skull'},
  {path='data/entities/animals/worm_tiny.xml',name='Worm tiny'},
  {path='data/entities/animals/wraith.xml',name='Wraith'},
  {path='data/entities/animals/wraith_glowing.xml',name='Wraith glowing'},
  {path='data/entities/animals/wraith_storm.xml',name='Wraith storm'},
  {path='data/entities/animals/zombie.xml',name='Zombie'},
  {path='data/entities/animals/zombie_weak.xml',name='Zombie weak'}
}
