local function animal(file, name, image)
  return {
    image='data/ui_gfx/animal_icons/'..(image or file)..'.png',
    path='data/entities/animals/'..file..'.xml',
    name=name,
  }
end

ANIMALS = {
  animal('acidshooter', 'Acidshooter'),
  animal('acidshooter_weak', 'Acidshooter weak'),
  animal('alchemist', 'Alchemist'),
  animal('ant', 'Ant'),
  animal('assassin', 'Assassin'),
  animal('barfer', 'Barfer'),
  animal('bat', 'Bat'),
  animal('bigbat', 'Bigbat'),
  animal('bigfirebug', 'Bigfirebug'),
  animal('bigzombie', 'Bigzombie'),
  animal('bigzombiehead', 'Bigzombiehead'),
  animal('bigzombietorso', 'Bigzombietorso'),
  animal('blob', 'Blob'),
  animal('bloodcrystal_physics', 'Bloodcrystal physics'),
  animal('bloom', 'Bloom'),
  animal('boss_alchemist/boss_alchemist', 'Boss alchemist', 'boss_alchemist'),
  animal('boss_centipede/boss_centipede', 'Boss three-eye - collect sampo in boss chamber to activate', 'boss_centipede'),
  animal('boss_centipede/boss_centipede_minion', 'Boss three-eye minion', 'boss_centipede'),
  animal('boss_dragon', 'Boss dragon'),
  animal('boss_limbs/boss_limbs', 'Boss limbs', 'boss_limbs'),
  animal('boss_limbs/slimeshooter_boss_limbs', 'Boss limbs minion', 'boss_limbs'), -- Missing own image
  animal('boss_pit/boss_pit', 'Boss pit', 'boss_pit'),
  animal('chest_leggy', 'Chest leggy'),
  animal('chest_mimic', 'Chest mimic'),
  animal('coward', 'Coward'),
  animal('crystal_physics', 'Crystal physics'),
  animal('deer', 'Deer'),
  animal('drone_shield', 'Drone Shield'),
  animal('drone_lasership', 'Drone lasership'),
  animal('drone_physics', 'Drone physics'),
  animal('duck', 'Duck'),
  animal('eel', 'Eel'),
  animal('elk', 'Elk'),
  animal('enlightened_alchemist', 'Enlightened alchemist'),
  animal('failed_alchemist', 'Failed alchemist'),
  animal('failed_alchemist_b', 'Failed alchemist b'),
  animal('firebug', 'Firebug'),
  animal('firemage', 'Firemage'),
  animal('firemage_weak', 'Firemage weak'),
  animal('fireskull', 'Fireskull'),
  animal('fireskull_weak', 'Fireskull weak', 'fireskull'),  -- Missing own image
  animal('fish', 'Fish'),
  animal('fish_large', 'Fish large'),
  animal('flamer', 'Flamer'),
  animal('fly', 'Fly'),
  animal('frog', 'Frog'),
  animal('frog_big', 'Frog big'),
  animal('fungus', 'Fungus'),
  animal('fungus_big', 'Fungus big'),
  animal('gazer', 'Gazer'),
  animal('ghoul', 'Ghoul'),
  animal('giant', 'Giant'),
  animal('giantshooter', 'Giantshooter'),
  animal('giantshooter_weak', 'Giantshooter weak'),
  animal('goblin_bomb', 'Goblin bomb'),
  animal('healerdrone_physics', 'Healerdrone physics'),
  animal('icer', 'Icer'),
  animal('iceskull', 'Iceskull'),
  animal('lasershooter', 'Lasershooter'),
  animal('longleg', 'Longleg'),
  animal('lukki/lukki', 'Lukki', 'lukki'),
  animal('lukki/lukki_creepy_long', 'Lukki creepy', 'lukki_longleg'),  -- Missing own image
  animal('lukki/lukki_longleg', 'Lukki longleg', 'lukki_longleg'),
  animal('lukki/lukki_tiny', 'Lukki tiny', 'lukki_tiny'),
  {path='data/entities/animals/lurker', name='Lurker', image="mods/raksa/files/gfx/animal_icons/lurker.png"},
  animal('maggot', 'Maggot'),
  animal('miner', 'Miner'),
  animal('miner_fire', 'Miner fire'),
  animal('miner_santa', 'Miner santa'),
  animal('miner_weak', 'Miner weak'),
  animal('miniblob', 'Miniblob'),
  animal('missilecrab', 'Missilecrab'),
  animal('monk', 'Monk'),
  animal('necromancer', 'Necromancer'),
  animal('necromancer_shop', 'Necromancer shop - Steve - Stevari'),
  animal('pebble_physics', 'Pebble physics'),
  animal('phantom_a', 'Phantom a'),
  animal('phantom_b', 'Phantom b'),
  animal('playerghost', 'Playerghost'),
  animal('rat', 'Rat'),
  animal('roboguard', 'Roboguard'),
  animal('scavenger_clusterbomb', 'Scavenger clusterbomb'),
  animal('scavenger_grenade', 'Scavenger grenade'),
  animal('scavenger_heal', 'Scavenger heal'),
  animal('scavenger_invis', 'Scavenger invis'),
  animal('scavenger_leader', 'Scavenger leader'),
  animal('scavenger_mine', 'Scavenger mine'),
  animal('scavenger_poison', 'Scavenger poison'),
  animal('scavenger_shield', 'Scavenger shield'),
  animal('scavenger_smg', 'Scavenger smg'),
  animal('scorpion', 'Scorpion'),
  animal('shaman', 'Shaman'),
  animal('sheep', 'Sheep'),
  animal('sheep_bat', 'Sheep bat'),
  animal('sheep_fly', 'Sheep fly'),
  animal('shooterflower', 'Shooterflower'),
  animal('shotgunner', 'Shotgunner'),
  animal('shotgunner_weak', 'Shotgunner weak'),
  animal('skullfly', 'Skullfly'),
  animal('skullrat', 'Skullrat'),
  animal('skycrystal_physics', 'Skycrystal physics'),
  animal('skygazer', 'Skygazer'),
  animal('slimeshooter', 'Slimeshooter'),
  animal('slimeshooter_nontoxic', 'Slimeshooter nontoxic', 'slimeshooter_weak'),
  animal('slimeshooter_weak', 'Slimeshooter weak'),
  animal('sniper', 'Sniper'),
  animal('spearbot', 'Spearbot'),
  animal('spitmonster', 'Spitmonster'),
  animal('statue', 'Statue'),
  animal('statue_physics', 'Statue physics'),
  animal('tank', 'Tank'),
  animal('tank_rocket', 'Tank rocket'),
  animal('tank_super', 'Tank super'),
  animal('tentacler', 'Tentacler'),
  animal('tentacler_small', 'Tentacler small'),
  animal('thundermage', 'Thundermage'),
  animal('thunderskull', 'Thunderskull'),
  animal('turret_left', 'Turret left'),
  animal('turret_right', 'Turret right'),
  animal('ultimate_killer', 'Ultimate killer - horror monster - friend'),
  animal('wand_ghost', 'Wand ghost'),
  animal('wizard_dark', 'Wizard dark'),
  animal('wizard_hearty', 'Wizard hearty'),
  animal('wizard_neutral', 'Wizard neutral'),
  animal('wizard_poly', 'Wizard poly'),
  animal('wizard_returner', 'Wizard returner'),
  animal('wizard_swapper', 'Wizard swapper'),
  animal('wizard_tele', 'Wizard tele'),
  animal('wizard_twitchy', 'Wizard twitchy'),
  animal('wizard_weaken', 'Wizard weaken'),
  animal('wizard_wither', 'Wizard wither'),
  animal('wolf', 'Wolf'),
  animal('worm_big', 'Worm big'),
  animal('worm_end', 'Worm end'),
  animal('worm_skull', 'Worm skull'),
  animal('worm_tiny', 'Worm tiny'),
  animal('wraith', 'Wraith'),
  animal('wraith_glowing', 'Wraith glowing'),
  animal('wraith_storm', 'Wraith storm'),
  animal('zombie', 'Zombie'),
  animal('zombie_weak', 'Zombie weak'),
  {path='data/entities/buildings/darkghost_crystal.xml', name='Darkghost'},
  {path='data/entities/buildings/ghost_crystal.xml', name='Ghost'},
  {path='data/entities/buildings/lasergun.xml', name='Lasergun'},
  {path='data/entities/buildings/lukki_eggs.xml', name='Lukki egg'},
  {path='data/entities/buildings/spidernest.xml', name='Spidernest'},
}
