PICKUPS = {
  {path='data/entities/items/pickup/bloodmoney_10.xml',name='Bloodmoney 10'},
  {path='data/entities/items/pickup/bloodmoney_50.xml',name='Bloodmoney 50'},
  {path='data/entities/items/pickup/bloodmoney_200.xml',name='Bloodmoney 200'},
  {path='data/entities/items/pickup/bloodmoney_1000.xml',name='Bloodmoney 1000'},
  {path='data/entities/items/pickup/bloodmoney_10000.xml',name='Bloodmoney 10000'},
  {path='data/entities/items/pickup/summon_portal_broken.xml',name='Broken summon portal spell'},
  {path='data/entities/items/pickup/broken_wand.xml',name='Broken wand'},
  {path='data/entities/items/pickup/cape.xml',name='Cape'},
  {path='data/entities/items/pickup/chest_leggy.xml',name='Chest leggy'},
  {path='data/entities/items/pickup/chest_random.xml',name='Chest random'},
  {path='data/entities/items/pickup/chest_random_super.xml',name='Chest random super'},
  {path='data/entities/animals/boss_alchemist/key.xml',name='Crystal Key'},
  {path='data/entities/items/pickup/egg_fire.xml',name='Egg fire'},
  {path='data/entities/items/pickup/egg_hollow.xml',name='Egg hollow'},
  {path='data/entities/items/pickup/egg_monster.xml',name='Egg monster'},
  {path='data/entities/items/pickup/egg_purple.xml',name='Egg purple'},
  {path='data/entities/items/pickup/egg_red.xml',name='Egg red'},
  {path='data/entities/items/pickup/egg_slime.xml',name='Egg slime'},
  {path='data/entities/items/pickup/egg_spiders.xml',name='Egg spiders'},
  {path='data/entities/items/pickup/egg_worm.xml',name='Egg worm'},
  {path='data/entities/items/pickup/essence_air.xml',name='Essence air'},
  {path='data/entities/items/pickup/essence_alcohol.xml',name='Essence alcohol'},
  {path='data/entities/items/pickup/essence_fire.xml',name='Essence fire'},
  {path='data/entities/items/pickup/essence_laser.xml',name='Essence laser'},
  {path='data/entities/items/pickup/essence_water.xml',name='Essence water'},
  {path='data/entities/items/pickup/goldnugget_10.xml',name='Goldnugget 10'},
  {path='data/entities/items/pickup/goldnugget_50.xml',name='Goldnugget 50'},
  {path='data/entities/items/pickup/goldnugget_200.xml',name='Goldnugget 200'},
  {path='data/entities/items/pickup/goldnugget_1000.xml',name='Goldnugget 1000'},
  {path='data/entities/items/pickup/goldnugget_10000.xml',name='Goldnugget 10000'},
  {path='data/entities/items/pickup/gourd.xml',name='Gourd'},
  {path='data/entities/items/pickup/heart.xml',name='Heart'},
  {path='data/entities/items/pickup/heart_better.xml',name='Heart better'},
  {path='data/entities/items/pickup/heart_evil.xml',name='Heart evil'},
  {path='data/entities/items/pickup/heart_fullhp.xml',name='Heart fullhp'},
  {path='data/entities/items/pickup/heart_fullhp_temple.xml',name='Heart fullhp temple'},
  {path='data/entities/items/flute.xml',name='Instrument Huilu'},
  {path='data/entities/items/kantele.xml',name='Instrument Kantele'},
  {path='data/entities/items/pickup/jar.xml',name='Jar'},
  {path='data/entities/items/pickup/physics_die.xml',name='Physics die'},
  {path='data/entities/items/pickup/potion.xml',name='Potion'},
  {path='data/entities/items/pickup/runestones/runestone_disc.xml',name='Runestone - disc'},
  {path='data/entities/items/pickup/runestones/runestone_fireball.xml',name='Runestone - fireball'},
  {path='data/entities/items/pickup/runestones/runestone_laser.xml',name='Runestone - laser'},
  {path='data/entities/items/pickup/runestones/runestone_lava.xml',name='Runestone - lava'},
  {path='data/entities/items/pickup/runestones/runestone_null.xml',name='Runestone - null'},
  {path='data/entities/items/pickup/runestones/runestone_slow.xml',name='Runestone - slow'},
  {path='data/entities/animals/boss_centipede/sampo.xml',name='Sampo'},
  {path='data/entities/items/pickup/spell_refresh.xml',name='Spell Refresher'},
  {path='data/entities/items/pickup/brimstone.xml',name='Stone - brimstone'},
  {path='data/entities/items/pickup/moon.xml',name='Stone - moon'},
  {path='data/entities/items/pickup/safe_haven.xml',name='Stone - safe haven'},
  {path='data/entities/items/pickup/thunderstone.xml',name='Stone - thunderstone'},
  {path='data/entities/items/pickup/waterstone.xml',name='Stone - waterstone'},	
}
