PROPS = {
  {path='data/entities/props/altar_torch.xml',name='Altar torch'},
  {path='data/entities/props/altar_torch_old.xml',name='Altar torch old'},
  {path='data/entities/props/banner.xml',name='Banner'},
  {path='data/entities/props/base_coalmine_structure.xml',name='Base coalmine structure'},
  {path='data/entities/props/boss_arena_statues.xml',name='Boss arena statues'},
  {path='data/entities/props/boss_arena_statue_1.xml',name='Boss arena statue 1'},
  {path='data/entities/props/boss_arena_statue_2.xml',name='Boss arena statue 2'},
  {path='data/entities/props/boss_arena_statue_3.xml',name='Boss arena statue 3'},
  {path='data/entities/props/boss_arena_statue_4.xml',name='Boss arena statue 4'},
  {path='data/entities/props/candle_1.xml',name='Candle 1'},
  {path='data/entities/props/candle_2.xml',name='Candle 2'},
  {path='data/entities/props/candle_3.xml',name='Candle 3'},
  {path='data/entities/props/coalmine_i_structure_01.xml',name='Coalmine i structure 01'},
  {path='data/entities/props/coalmine_i_structure_02.xml',name='Coalmine i structure 02'},
  {path='data/entities/props/coalmine_large_structure_01.xml',name='Coalmine large structure 01'},
  {path='data/entities/props/coalmine_large_structure_02.xml',name='Coalmine large structure 02'},
  {path='data/entities/props/coalmine_structure_01.xml',name='Coalmine structure 01'},
  {path='data/entities/props/coalmine_structure_02.xml',name='Coalmine structure 02'},
  {path='data/entities/props/dripping_acid_gas.xml',name='Dripping acid gas'},
  {path='data/entities/props/dripping_oil.xml',name='Dripping oil'},
  {path='data/entities/props/dripping_radioactive.xml',name='Dripping radioactive'},
  {path='data/entities/props/dripping_water.xml',name='Dripping water'},
  {path='data/entities/props/dripping_water_heavy.xml',name='Dripping water heavy'},
  {path='data/entities/props/dummy_target.xml',name='Dummy target'},
  {path='data/entities/props/excavationsite_machine_3b.xml',name='Excavationsite machine 3b'},
  {path='data/entities/props/excavationsite_machine_3c.xml',name='Excavationsite machine 3c'},
  {path='data/entities/props/furniture_bed.xml',name='Furniture bed'},
  {path='data/entities/props/furniture_bunk.xml',name='Furniture bunk'},
  {path='data/entities/props/furniture_castle_chair.xml',name='Furniture castle chair'},
  {path='data/entities/props/furniture_castle_divan.xml',name='Furniture castle divan'},
  {path='data/entities/props/furniture_castle_statue.xml',name='Furniture castle statue'},
  {path='data/entities/props/furniture_castle_table.xml',name='Furniture castle table'},
  {path='data/entities/props/furniture_castle_wardrobe.xml',name='Furniture castle wardrobe'},
  {path='data/entities/props/furniture_cryopod.xml',name='Furniture cryopod'},
  {path='data/entities/props/furniture_dresser.xml',name='Furniture dresser'},
  {path='data/entities/props/furniture_footlocker.xml',name='Furniture footlocker'},
  {path='data/entities/props/furniture_locker.xml',name='Furniture locker'},
  {path='data/entities/props/furniture_rocking_chair.xml',name='Furniture rocking chair'},
  {path='data/entities/props/furniture_stool.xml',name='Furniture stool'},
  {path='data/entities/props/furniture_table.xml',name='Furniture table'},
  {path='data/entities/props/furniture_tombstone_01.xml',name='Furniture tombstone 1'},
  {path='data/entities/props/furniture_tombstone_02.xml',name='Furniture tombstone 2'},
  {path='data/entities/props/furniture_tombstone_03.xml',name='Furniture tombstone 3'},
  {path='data/entities/props/furniture_wardrobe.xml',name='Furniture wardrobe'},
  {path='data/entities/props/furniture_wood_chair.xml',name='Furniture wood chair'},
  {path='data/entities/props/furniture_wood_table.xml',name='Furniture wood table'},
  {path='data/entities/misc/greed_curse/greed_crystal.xml',name='Greed Crystal'},
  {path='data/entities/props/ladder_long.xml',name='Ladder long'},
  {path='data/entities/props/mountain_left_entrance_grass.xml',name='Mountain left entrance grass'},
  {path='data/entities/props/music_machines/music_machine_00.xml',name='Music machine 1'},
  {path='data/entities/props/music_machines/music_machine_01.xml',name='Music machine 2'},
  {path='data/entities/props/music_machines/music_machine_02.xml',name='Music machine 3'},
  {path='data/entities/props/music_machines/music_machine_03.xml',name='Music machine 4'},
  {path='data/entities/props/physics_barrel_burning.xml',name='Physics barrel burning'},
  {path='data/entities/props/physics_barrel_oil.xml',name='Physics barrel oil'},
  {path='data/entities/props/physics_barrel_radioactive.xml',name='Physics barrel radioactive'},
  {path='data/entities/props/physics_barrel_water.xml',name='Physics barrel water'},
  {path='data/entities/props/physics_bed.xml',name='Physics bed'},
  {path='data/entities/props/physics_bone_01.xml',name='Physics bone 01'},
  {path='data/entities/props/physics_bone_02.xml',name='Physics bone 02'},
  {path='data/entities/props/physics_bone_03.xml',name='Physics bone 03'},
  {path='data/entities/props/physics_bone_04.xml',name='Physics bone 04'},
  {path='data/entities/props/physics_bone_05.xml',name='Physics bone 05'},
  {path='data/entities/props/physics_bone_06.xml',name='Physics bone 06'},
  {path='data/entities/props/physics_bottle_blue.xml',name='Physics bottle blue'},
  {path='data/entities/props/physics_bottle_green.xml',name='Physics bottle green'},
  {path='data/entities/props/physics_bottle_red.xml',name='Physics bottle red'},
  {path='data/entities/props/physics_bottle_yellow.xml',name='Physics bottle yellow'},
  {path='data/entities/props/physics_box_explosive.xml',name='Physics box explosive'},
  {path='data/entities/props/physics_box_harmless.xml',name='Physics box harmless'},
  {path='data/entities/props/physics_box_harmless_small.xml',name='Physics box harmless small'},
  {path='data/entities/props/physics_brewing_stand.xml',name='Physics brewing stand'},
  {path='data/entities/props/physics_bucket.xml',name='Physics bucket'},
  {path='data/entities/props/physics_campfire.xml',name='Physics campfire'},
  {path='data/entities/props/physics_candle_1.xml',name='Physics candle 1'},
  {path='data/entities/props/physics_candle_2.xml',name='Physics candle 2'},
  {path='data/entities/props/physics_candle_3.xml',name='Physics candle 3'},
  {path='data/entities/props/physics_cart.xml',name='Physics cart'},
  {path='data/entities/props/physics_chain_torch.xml',name='Physics chain torch'},
  {path='data/entities/props/physics_chain_torch_blue.xml',name='Physics chain torch blue'},
  {path='data/entities/props/physics_chain_torch_ghostly.xml',name='Physics chain torch ghostly'},
  {path='data/entities/props/physics_chair_1.xml',name='Physics chair 1'},
  {path='data/entities/props/physics_chair_2.xml',name='Physics chair 2'},
  {path='data/entities/props/physics_chandelier.xml',name='Physics chandelier'},
  {path='data/entities/props/physics_crate.xml',name='Physics crate'},
  {path='data/entities/props/physics_electricity_source.xml',name='Physics electricity source'},
  {path='data/entities/props/physics_gem.xml',name='Physics gem'},
  {path='data/entities/props/physics_glass_shard_01.xml',name='Physics glass shard 01'},
  {path='data/entities/props/physics_glass_shard_02.xml',name='Physics glass shard 02'},
  {path='data/entities/props/physics_glass_shard_03.xml',name='Physics glass shard 03'},
  {path='data/entities/props/physics_glass_shard_04.xml',name='Physics glass shard 04'},
  {path='data/entities/props/physics_lantern.xml',name='Physics lantern'},
  {path='data/entities/props/physics_lantern_small.xml',name='Physics lantern small'},
  {path='data/entities/props/physics_logo.xml',name='Physics logo'},
  {path='data/entities/props/physics_logo_1.xml',name='Physics logo 1'},
  {path='data/entities/props/physics_logo_2.xml',name='Physics logo 2'},
  {path='data/entities/props/physics_logo_3.xml',name='Physics logo 3'},
  {path='data/entities/props/physics_minecart.xml',name='Physics minecart'},
  {path='data/entities/props/physics_mining_lamp.xml',name='Physics mining lamp'},
  {path='data/entities/props/physics_pressure_tank.xml',name='Physics pressure tank'},
  {path='data/entities/props/physics_propane_tank.xml',name='Physics propane tank'},
  {path='data/entities/props/physics_ragdoll_part.xml',name='Physics ragdoll part'},
  {path='data/entities/props/physics_ragdoll_part_electrified.xml',name='Physics ragdoll part electrified'},
  {path='data/entities/props/physics_ragdoll_part_exploding.xml',name='Physics ragdoll part exploding'},
  {path='data/entities/props/physics_sandbag.xml',name='Physics sandbag'},
  {path='data/entities/props/physics_seamine.xml',name='Physics seamine'},
  {path='data/entities/props/physics_skateboard.xml',name='Physics skateboard'},
  {path='data/entities/props/physics_skull_01.xml',name='Physics skull 01'},
  {path='data/entities/props/physics_skull_02.xml',name='Physics skull 02'},
  {path='data/entities/props/physics_skull_03.xml',name='Physics skull 03'},
  {path='data/entities/props/physics_statue.xml',name='Physics statue'},
  {path='data/entities/props/physics_stone_01.xml',name='Physics stone 01'},
  {path='data/entities/props/physics_stone_02.xml',name='Physics stone 02'},
  {path='data/entities/props/physics_stone_03.xml',name='Physics stone 03'},
  {path='data/entities/props/physics_stone_04.xml',name='Physics stone 04'},
  {path='data/entities/props/physics_table.xml',name='Physics table'},
  {path='data/entities/props/physics_templedoor.xml',name='Physics templedoor'},
  {path='data/entities/props/physics_templedoor2.xml',name='Physics templedoor2'},
  {path='data/entities/props/physics_torch_stand.xml',name='Physics torch stand'},
  {path='data/entities/props/physics_torch_stand_blue.xml',name='Physics torch stand blue'},
  {path='data/entities/props/physics_torch_stand_intro.xml',name='Physics torch stand intro'},
  {path='data/entities/props/physics_trap_circle_acid.xml',name='Physics trap circle acid'},
  {path='data/entities/props/physics_trap_electricity.xml',name='Physics trap electricity'},
  {path='data/entities/props/physics_trap_electricity_enabled.xml',name='Physics trap electricity enabled'},
  {path='data/entities/props/physics_trap_ignite.xml',name='Physics trap ignite'},
  {path='data/entities/props/physics_trap_ignite_a.xml',name='Physics trap ignite a'},
  {path='data/entities/props/physics_trap_ignite_b.xml',name='Physics trap ignite b'},
  {path='data/entities/props/physics_trap_ignite_enabled.xml',name='Physics trap ignite enabled'},
  {path='data/entities/props/physics_tubelamp.xml',name='Physics tubelamp'},
  {path='data/entities/props/physics_vase.xml',name='Physics vase'},
  {path='data/entities/props/physics_vase_longleg.xml',name='Physics vase longleg'},
  {path='data/entities/props/physics_wheel.xml',name='Physics wheel'},
  {path='data/entities/props/physics_wheel_small.xml',name='Physics wheel small'},
  {path='data/entities/props/physics_wheel_stand_01.xml',name='Physics wheel stand 01'},
  {path='data/entities/props/physics_wheel_stand_02.xml',name='Physics wheel stand 02'},
  {path='data/entities/props/physics_wheel_stand_03.xml',name='Physics wheel stand 03'},
  {path='data/entities/props/physics_wheel_tiny.xml',name='Physics wheel tiny'},
  {path='data/entities/props/pressure_plate.xml',name='Pressure plate'},
  {path='data/entities/props/root_grower.xml',name='Root grower'},
  {path='data/entities/props/root_grower_branch.xml',name='Root grower branch'},
  {path='data/entities/props/root_grower_fruit.xml',name='Root grower fruit'},
  {path='data/entities/props/root_grower_leaf.xml',name='Root grower leaf'},
  {path='data/entities/props/sarcophagus.xml',name='Sarcophagus'},
  {path='data/entities/props/sarcophagus_evil.xml',name='Sarcophagus evil'},
  {path='data/entities/props/statue.xml',name='Statue'},
  {path='data/entities/props/statue_back.xml',name='Statue back'},
  {path='data/entities/buildings/statue_hand_1.xml',name='Statue hand'},
  {path='data/entities/props/stonepile.xml',name='Stonepile'},
  {path='data/entities/props/temple_pressure_plate.xml',name='Temple pressure plate'},
  {path='data/entities/props/_test_physics_heavy.xml',name='test physics heavy'},
  {path='data/entities/props/_test_physics_light.xml',name='test physics light'},
  {path='data/entities/props/vault_apparatus_01.xml',name='Vault apparatus 01'},
  {path='data/entities/props/vault_apparatus_02.xml',name='Vault apparatus 02'},
  {path='data/entities/props/vault_machine_1.xml',name='Vault machine 1'},
  {path='data/entities/props/vault_machine_2.xml',name='Vault machine 2'},
  {path='data/entities/props/vault_machine_3.xml',name='Vault machine 3'},
  {path='data/entities/props/vault_machine_4.xml',name='Vault machine 4'},
  {path='data/entities/props/vault_machine_5.xml',name='Vault machine 5'},
  {path='data/entities/props/vault_machine_6.xml',name='Vault machine 6'},
  {path='data/entities/buildings/physics_worm_deflector_crystal.xml',name='Worm Crystal'}
}
