BRUSHES = {
  {
    name="1px brush",
    offset_x=3,
    offset_y=3,
    reticle_file="mods/raksa/files/wands/entwand/brushes/1_reticle.png",
    brush_file="mods/raksa/files/wands/entwand/brushes/1_brush.png",
    icon_file="mods/raksa/files/wands/entwand/brushes/1_icon.png",
  },
  {
    name="2px brush",
    offset_x=4,
    offset_y=4,
    reticle_file="mods/raksa/files/wands/entwand/brushes/2_reticle.png",
    brush_file="mods/raksa/files/wands/entwand/brushes/2_brush.png",
    icon_file="mods/raksa/files/wands/entwand/brushes/2_icon.png",
  },
  {
    name="5px brush",
    offset_x=11,
    offset_y=11,
    reticle_file="mods/raksa/files/wands/entwand/brushes/5_reticle.png",
    brush_file="mods/raksa/files/wands/entwand/brushes/5_brush.png",
    icon_file="mods/raksa/files/wands/entwand/brushes/5_icon.png",
  },
  {
    name="10px brush",
    offset_x=15,
    offset_y=15,
    reticle_file="mods/raksa/files/wands/entwand/brushes/10_reticle.png",
    brush_file="mods/raksa/files/wands/entwand/brushes/10_brush.png",
    icon_file="mods/raksa/files/wands/entwand/brushes/10_icon.png",
  },
  {
    name="40px long horizontal",
    offset_x=60,
    offset_y=1.5,
    reticle_file="mods/raksa/files/wands/entwand/brushes/40_lh_reticle.png",
    brush_file="mods/raksa/files/wands/entwand/brushes/40_lh_brush.png",
    icon_file="mods/raksa/files/wands/entwand/brushes/40_lh_icon.png",
  },
  {
    name="40px long vertical",
    offset_x=1.5,
    offset_y=60,
    reticle_file="mods/raksa/files/wands/entwand/brushes/40_lv_reticle.png",
    brush_file="mods/raksa/files/wands/entwand/brushes/40_lv_brush.png",
    icon_file="mods/raksa/files/wands/entwand/brushes/40_lv_icon.png",
  },
  {
    name="Cauldron",
    offset_x=44,
    offset_y=42,
    reticle_file="mods/raksa/files/wands/entwand/brushes/cauldron_reticle.png",
    brush_file="mods/raksa/files/wands/entwand/brushes/cauldron_brush.png",
    icon_file="mods/raksa/files/wands/entwand/brushes/cauldron_icon.png",
  },
}
